### ISSUE TITLE
Support for licenseDebugReport or licenseReleaseReport using Gradle 4.0 / Android

### ISSUE THREAD

**Issue by arocha55** [jaredsburrows/gradle-license-plugin#14]
Hello,

I'm trying to run licenseDebugReport or licenseReleaseReport on my Android app using Gradle 4.0 and Android Plugin Version 3.0.0-alpha2. The task fails to run, see error report below:

```
arocha$ ./gradlew :android:licenseDebugReport --stacktrace
Parallel execution with configuration on demand is an incubating feature.
Configuration 'compile' in project ':android' is deprecated. Use 'implementation' instead.
:android:licenseDebugReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:licenseDebugReport'.
> Resolving configuration 'debugCompile' directly is not allowed

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':android:licenseDebugReport'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:98)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:248)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:239)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:114)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:239)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:226)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:120)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:101)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:527)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:95)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.IllegalStateException: Resolving configuration 'debugCompile' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:885)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:458)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:453)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at com.jaredsburrows.license.LicenseReportTask$_generatePOMInfo_closure2.doCall(LicenseReportTask.groovy:68)
        at com.jaredsburrows.license.LicenseReportTask.generatePOMInfo(LicenseReportTask.groovy:67)
        at com.jaredsburrows.license.LicenseReportTask.licenseReport(LicenseReportTask.groovy:37)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:139)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:132)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:706)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:689)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:115)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.execute(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:114)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:90)
        ... 26 more


BUILD FAILED in 0s
1 actionable task: 1 executed, 0 avoided (0%)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:licenseDebugReport'.
> Resolving configuration 'debugCompile' directly is not allowed
```

I was not having this issue prior to updating to Gradle 4.0. Any ETA on when can we expect support for latest Gradle version?

Thanks,
Alex

**Comment by jaredsburrows** [comment]
This project is build using Gradle 4.0, I am guessing it is the Android gradle plugin alpha?

**Comment by jaredsburrows** [comment]
@arocha55 Alright, I tested this with Gradle 4.0 but not `3.0.0-alpha2`.

**Comment by jaredsburrows** [comment]
Looks like I need to add support for `api` and `implementation`.

**Comment by MinkiPan** [comment]
any updates on this one? I am getting the same error on android studio Beta6
it would be great if you can fix this

**Comment by jaredsburrows** [comment]
Are you see that error or this one? With beta6? I am looking into supporting AGP 3, a lot of the tests break.

**Comment by MinkiPan** [comment]
same error as @arocha55 posted

**Comment by jaredsburrows** [comment]
@arocha55 @MinkiPan The initial `> Resolving configuration 'debugCompile' directly is not allowed` error is fixed here: https://github.com/jaredsburrows/gradle-license-plugin/commit/924fc04d6ce1978c135fda5c6a3008bba1eb90c3.

I have started to add support for `api` and `implementation` here: https://github.com/jaredsburrows/gradle-license-plugin/commit/dec05c6fe71ba8066f755e1d58bc77bba1943a89. I added integration tests to test this out, however the `SNAPSHOT` does not see to work on my test project.

Snapshot: https://oss.jfrog.org/webapp/#/builds/gradle-license-plugin
Test Project: https://github.com/jaredsburrows/android-gif-example

**Comment by agustinsivoplas** [comment]
How to test the 0.7 SNAPSHOT version? I am not able to test it. I am stuck in the same problem

**Comment by jaredsburrows** [comment]
@agustinsivoplas Just updated the README.md: https://github.com/jaredsburrows/gradle-license-plugin#download.

**Comment by jaredsburrows** [comment]
I have just released `0.7.0`.

**Comment by MinkiPan** [comment]
works for me now on AS3.0 RC2

**Comment by jaredsburrows** [comment]
Good to hear!

**Comment by agustinsivoplas** [comment]
FYI, works for me too!

**Comment by jaredsburrows** [comment]
@agustinsivoplas It should, I have a test for subprojects here: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/test/groovy/com/jaredsburrows/license/LicenseReportTaskSpec.groovy#L1057.
