### ISSUE TITLE
Cannot change usage of dependency configuration 'xxx' after it has been included in dependency resolution.

### ISSUE THREAD

**Issue by sergeys-opera** [jaredsburrows/gradle-license-plugin#338]
The plugin spits a lot of warnings while running its `licenseDebugReport` task:
```
Task :ui:licenseDebugReport
Cannot resolve configuration androidTestAnnotationProcessor
org.gradle.api.InvalidUserDataException: Cannot change usage of dependency configuration ':ui:androidTestAnnotationProcessor' after it has been included in dependency resolution.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1551)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1510)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.setCanBeResolved(DefaultConfiguration.java:1880)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.setCanBeResolved(Unknown Source)
	at com.jaredsburrows.license.LicenseReportTask.setupEnvironment(LicenseReportTask.kt:161)
	at com.jaredsburrows.license.LicenseReportTask.licenseReport(LicenseReportTask.kt:97)
... a lot more
```
Some warnings contain a slightly different error message:
```
Cannot resolve configuration testFixturesRuntimeOnly
org.gradle.api.GradleException: Cannot change the allowed usage of configuration ':ui:testFixturesRuntimeOnly', as it has been locked.
```

AGP version: 8.1.0
Plugin version: 0.9.3

**Comment by t-beckmann** [comment]
Actually I think setting `configuration.isCanBeResolved = true ` at https://github.com/jaredsburrows/gradle-license-plugin/blob/master/gradle-license-plugin/src/main/kotlin/com/jaredsburrows/license/LicenseReportTask.kt#L161 is not necessary.

**Comment by jaredsburrows** [comment]
Is this the same as https://github.com/jaredsburrows/gradle-license-plugin/issues/234? Also, why is `configuration.isCanBeResolved = true` not necessary?

**Comment by sergeys-opera** [comment]
> Is this the same as https://github.com/jaredsburrows/gradle-license-plugin/issues/234?

Probably, yes.

My workaround for this issue is:
```
    // Silence excessive warning messages from "license[Debug|Release]Report" task,
    // see https://github.com/jaredsburrows/gradle-license-plugin/issues/338
    forEachTask(predicate = { it.name == "license${variantName}Report" }) {
        it.notCompatibleWithConfigurationCache("Not implemented")
        (it.logger as ContextAwareTaskLogger).setMessageRewriter { logLevel, message ->
            if (logLevel == LogLevel.WARN && message.startsWith(
                    "Cannot resolve configuration"
                )
            ) null else message
        }
    }
```

I couldn't get rid of the error messages by using `mustRunAfter`/`dependsOn` as suggested in #234. The project where I see the issue is an Android project if that matters.
I also call `notCompatibleWithConfigurationCache` on the license task as it's not yet (version `0.9.4`) compatible with the configuration cache.

**Comment by jaredsburrows** [comment]
I have had this plugin applied to a project of mine - https://github.com/jaredsburrows/android-gif-search. It has now been migrated to ksp instead of `kapt` / `annotationProcessor`. I have not been able to reproduce this.

I can look into removing these warnings produced by the plugin scanning the configurations.

**Comment by t-beckmann** [comment]
For those interested, the meaning of those flags is discussed at https://docs.gradle.org/7.5.1/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs.

Setting the isCanBeResolved turns producer and internal configurations to consumers. In the project I am working on doing so **has unexpected side-effects on the Gradle build cache**, so that it no longer matches!

Admittedly I do not fully understand the effect on the build cache, but I could resolve it by running the license plugin in a separate Gradle invocation separate from all other tasks. My guess is changing isCanBeResolved leads to a different order of dependencies in other configurations...

I am saying changing the flag should not be necessary because a configuration that is not resolvable contributes files to the build only if it is resolved indirectly via some other configuration extending upon it. But in that case the files in question are part of the extending configuration as well and so are picked up by the license plugin nevertheless.

**Comment by sergeys-opera** [comment]
Hey @jaredsburrows, I noticed that you fixed the configuration cache issues here https://github.com/jaredsburrows/gradle-license-plugin/pull/735. Would it be possible to release a new version of the plugin any time soon?
The license task is the last task in our project that doesn't support the configuration cache.

**Comment by jaredsburrows** [comment]
@sergeys-opera done via https://github.com/jaredsburrows/gradle-license-plugin/releases/tag/0.9.9.

**Comment by jaredsburrows** [comment]
Fixed by #735.
