### ISSUE TITLE
License report task crashes with a StackOverflowError

### ISSUE THREAD

**Issue by devconsole** [jaredsburrows/gradle-license-plugin#374]
As soon as I include a dependency on androidx.camera:camera-camera2:1.3.0 in my Android project the license report task fails.

> ./gradlew --stacktrace licenseDebugReport
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':xxx:licenseDebugReport'.
        at ...
Caused by: java.lang.StackOverflowError
        at ...
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at com.jaredsburrows.license.LicenseReportTask.getParentPomFile(LicenseReportTask.kt:301)
        at com.jaredsburrows.license.LicenseReportTask.findLicenses(LicenseReportTask.kt:436)
        at com.jaredsburrows.license.LicenseReportTask.findLicenses(LicenseReportTask.kt:434)
        at com.jaredsburrows.license.LicenseReportTask.findLicenses(LicenseReportTask.kt:434)
        ...

> ./gradlew --info licenseDebugReport
...
Project, AutoValue Annotations, has no license in POM file.
Project, AutoValue Parent, has no license in POM file.
Project, AutoValue Parent, has no license in POM file.
Project, AutoValue Parent, has no license in POM file.
...

Also, could you include the artifact ID in the log output, in addition to the project name?

**Comment by jaredsburrows** [comment]
Are you still seeing this? I believe this works just fine for me:
<img width="504" alt="Screenshot 2024-01-29 at 3 04 55 PM" src="https://github.com/jaredsburrows/gradle-license-plugin/assets/1739848/4a20d8ce-d527-480e-90f3-f86b9e0bcff5">
