### ISSUE TITLE
Does this also works for flutter project

### ISSUE THREAD

**Issue by vballem** [jaredsburrows/gradle-license-plugin#458]
Hi,

I have  some modules that is developed in flutter which are all used in my android app. when I integrate this library, build failed.
Kindly let us know?.

`Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.gradle.plugin.KotlinGradleBuildServices

Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: KOTLIN_STAT_ENABLED_PROPERTY [in thread "Daemon worker Thread 2"]

Cause 1: java.lang.NullPointerException: Cannot invoke method substring() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at FlutterPlugin$_detectLowCompileSdkVersion_closure15$_closure41$_closure42.doCall(/Users/../fvm/versions/2.10.5/packages/flutter_tools/gradle/flutter.gradle:422)`

**Comment by jaredsburrows** [comment]
Can you share your build.gradle file? This looks like it is coming from `fvm/versions/2.10.5/packages/flutter_tools/gradle/flutter.gradle:422`.
